import { Player } from "bdsx/bds/player";
import { Games } from ".";
import { CommandOrigin } from "bdsx/bds/commandorigin";
import { CommandOutput } from "bdsx/bds/command";
import { Vec3 } from "bdsx/bds/blockpos";
export declare function getPlayerByName(name: string): Player | null;
export declare function spectate(pl: Player): void;
export declare function spectateStop(pl: Player, tp?: Vec3): void;
export declare function stopGame(): void;
export declare function startGame(game: Games, players: Player[], sec: number, title?: string): Promise<string[] | null>;
export declare function countdownActionbar(sec: number, pls: string[], actionbar: boolean, title?: string): Promise<boolean>;
export declare function joinqueue(origin: CommandOrigin, output: CommandOutput): void;
export declare function leavequeue(origin: CommandOrigin, output: CommandOutput): void;
